version: "3.7"
services:
  activitycompleted_service:
    build: 
      context: ./ActivityCompletedService/
    volumes:
      - "./ActivityCompletedService:/usr/app"
    ports:
      - "3001:3001"
      - "5672:5672"
    networks:
      - "webnet"

  activityassessment_service:
    build: 
      context: ./ActivityAssessmentService/
    volumes:
      - "./ActivityAssessmentService:/usr/app"
    ports:
      - "3002:3002"
      - "5673:5672"
    networks:
      - "webnet"
      
networks: 
  webnet:
    driver: bridge